### ISSUE TITLE
could not resolve punycode

### ISSUE THREAD

**Issue by andrewluetgers** [pngwn/mdsvex-playground#1]
Trying to run this and got the following error, any ideas?

'punycode' is imported by node_modules/mdsvex/dist/main.es.js, but could not be resolved – treating it as an external dependency

**Comment by pngwn** [comment]
I've had this myself but I never got round to sorting it satisfactorily, It's something do with `markdown-it`. I think I just installed `punycode` directly in the repository to fix the error but it is listed in the dependencies so it should already be there when you `npm i`. Try `npm i punycode` see if that helps in the meantime and I'll try to resolve this properly as soon as I can.

**Comment by pngwn** [comment]
punycode is no longer used as of 0.8.
